### ISSUE TITLE
Error: "Unrecognized option: -"

### ISSUE THREAD

**Issue by HunterFrisby** [BulletTime/vscode-xslt-transform#3]
I get an error from Saxon "Unrecognized option: -" when i try to run the transform.

**Comment by sagneessens** [comment]
Can you provide me with more information:
- OS
- version of vscode
- version of saxon

**Comment by HunterFrisby** [comment]
- Windows 10
- VSCode 1.45.0
- Saxon-EE 9.9.1.6J

Thanks!

**Comment by sagneessens** [comment]
I can't seem to replicate this error, although I'm working on different versions:

- Windows 10
- VSCode 1.44.2
- Saxon-HE 9.9.1.6J

Did you configure the extension?
Can you try and check if it is working with the Saxon-HE version?

**Comment by HunterFrisby** [comment]
I tried Saxon-HE 9.9.1.7J as well as VSCode 1.44.2, neither seemed to change the output.

**_Output:_**
> Unrecognized option: -
> Saxon-HE 9.9.1.7J from Saxonica
> Usage: see http://www.saxonica.com/documentation/index.html#!using-xsl/commandline
> Format: net.sf.saxon.Transform options params
> Options available: -? -a -catalog -config -cr -diag -dtd -ea -expand -explain -export -ext -im -init -it -jit -l -lib -license -m -nogo -now -o -opt -or -outval -p -quit -r -relocate -repeat -s -sa -scmin -strip -t -T -target -TB -threads -TJ -Tlevel -Tout -TP -traceout -tree -u -val -versionmsg -warnings -x -xi -xmlversion -xsd -xsdversion -xsiloc -xsl -y
> Use -XYZ:? for details of option XYZ
> Params: 
>   param=value           Set stylesheet string parameter
>   +param=filename       Set stylesheet document parameter
>   ?param=expression     Set stylesheet parameter using XPath
>   !param=value          Set serialization parameter

**Comment by redhawk07** [comment]
Had the same issue and found the reason:
If the file path contains spaces, the tool fails to work.
In the given scenario, the path contained a minus sign wrapped by two spaces: " - ".
The path handling should be corrected (also for the configuration of the location of the saxon tool; there otherwise you have to add quotation marks at begin and end of the tool path)
